/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progpatternsmidtermexam;

/**
 *
 * @author 2319522
 */
public class ProgPatternsMidtermExam extends javax.swing.JFrame {

    /**
     * Creates new form ProgPatternsMidtermExam
     */
    public ProgPatternsMidtermExam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAccountButton = new javax.swing.JButton();
        payInterestButton = new javax.swing.JButton();
        switchLanguageButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountTextArea = new javax.swing.JTextArea();
        interestTextField = new javax.swing.JTextField();
        interestLabel = new javax.swing.JLabel();
        updateInterestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        addAccountButton.setText("Add Account");
        addAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountButtonActionPerformed(evt);
            }
        });

        payInterestButton.setText("Pay Interest");
        payInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payInterestButtonActionPerformed(evt);
            }
        });

        switchLanguageButton.setText("Switch To French");
        switchLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchLanguageButtonActionPerformed(evt);
            }
        });

        accountTextArea.setColumns(20);
        accountTextArea.setRows(5);
        jScrollPane1.setViewportView(accountTextArea);

        interestLabel.setText("Interest");

        updateInterestButton.setText("Update Interest");
        updateInterestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInterestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(switchLanguageButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(payInterestButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addAccountButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(interestLabel)
                        .addGap(43, 43, 43)
                        .addComponent(interestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateInterestButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switchLanguageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAccountButton)
                    .addComponent(payInterestButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateInterestButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setText();
    }//GEN-LAST:event_formWindowOpened

    private void addAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountButtonActionPerformed
        AddAccount addAccount = new AddAccount();
        addAccount.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addAccountButtonActionPerformed

    private void payInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payInterestButtonActionPerformed
        BankController controller = new BankController();
        controller.payInterest();
        setText();
    }//GEN-LAST:event_payInterestButtonActionPerformed

    private void switchLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchLanguageButtonActionPerformed
        Internationalization.switchLocale();
        setText();
    }//GEN-LAST:event_switchLanguageButtonActionPerformed

    private void updateInterestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInterestButtonActionPerformed
        BankController controller = new BankController();
        controller.setInterestRate(Double.parseDouble(interestTextField.getText()));
        setText();
    }//GEN-LAST:event_updateInterestButtonActionPerformed

    private void setText() {
        addAccountButton.setText(Internationalization.getMessage("addAccountButton"));
        payInterestButton.setText(Internationalization.getMessage("payInterestButton"));
        switchLanguageButton.setText(Internationalization.getMessage("switchLanguageButton"));
        updateInterestButton.setText(Internationalization.getMessage("updateInterestButton"));
        interestLabel.setText(Internationalization.getMessage("interestLabel"));
        accountTextArea.setText(new BankView().getString());
        BankController controller = new BankController();
        interestTextField.setText(String.valueOf(controller.getInterestRate()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgPatternsMidtermExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgPatternsMidtermExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgPatternsMidtermExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgPatternsMidtermExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgPatternsMidtermExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea accountTextArea;
    private javax.swing.JButton addAccountButton;
    private javax.swing.JLabel interestLabel;
    private javax.swing.JTextField interestTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payInterestButton;
    private javax.swing.JButton switchLanguageButton;
    private javax.swing.JButton updateInterestButton;
    // End of variables declaration//GEN-END:variables
}
